### PR TITLE
chore(package): update atom-package-deps to version 4.4.0

### LINKED ISSUE #56: An in-range update of atom-package-deps is breaking the build 🚨
## Version **4.4.0** of [atom-package-deps](https://github.com/steelbrain/package-deps) just got published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/AtomLinter/linter-scalac/compare/greenkeeper%2Fatom-package-deps-4.4.0">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      atom-package-deps
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      4.3.1
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      dependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

As atom-package-deps is a direct dependency of this project **this is very likely breaking your project right now**. If other packages depend on you it’s very likely also breaking them.
I recommend you give this issue a very high priority. I’m sure you can resolve this :muscle:

---

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build is in progress [Details](https://travis-ci.org/AtomLinter/linter-scalac/builds/201044698)

- ❌ **ci/circleci** Your tests failed on CircleCI [Details](https://circleci.com/gh/AtomLinter/linter-scalac/72?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 19 commits .</p>
<ul>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/85b3cdb90d8a30ce9538dfc828120510a750a653"><code>85b3cdb</code></a> <code>:arrow_up: Bump version to 4.4.0</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/d37c1228548209b7a31b0efee92f3b483005e6d7"><code>d37c122</code></a> <code>:no_entry: Ignore decls and flowconfig in npm</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/e9a9502482cd8f376049ca1184592b1017b4d095"><code>e9a9502</code></a> <code>:memo: Document changes in CHANGELOG</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/add57005207229863e59cc1aa51ac2a1c6edb18e"><code>add5700</code></a> <code>:memo: Add screenshots to README</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/047dd2c508696825d6e712060466776a5fbaad38"><code>047dd2c</code></a> <code>:memo: Document new second param in Docs</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/d3877d456997ef806064733f6fc319cf6469cc12"><code>d3877d4</code></a> <code>:fire: Remove todo because done</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/2835096680d4f1bc17c7b9ff7b2b027e10b2a5fe"><code>2835096</code></a> <code>Merge pull request #78 from steelbrain/steelbrain/add-second-param</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/dd30efaf705fc396cec9b799bc4ac6f73ea352dd"><code>dd30efa</code></a> <code>:art: Address reviewer's comments</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/8ecfc9613b568131d871105447d6522507a6f80a"><code>8ecfc96</code></a> <code>🆕  Remember when user presses Never</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/67ac8c3585fa924e9e572e01e7414c2c646a7a5f"><code>67ac8c3</code></a> <code>:new: Add a never button</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/9e0a14ec8846920b5153ed147a0c8b2250c75888"><code>9e0a14e</code></a> <code>:new: Add posibility for Never option</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/76e0f0e93bc61d28ec66fda3060fa8b15f0d10f4"><code>76e0f0e</code></a> <code>:new: Add second param to prompt user to install</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/8322fe42ef31c5a5ab05055147c4b6328a1a41ac"><code>8322fe4</code></a> <code>Merge pull request #77 from archcorsair/master</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/3522341bb0a72c52bfd62a8c10dfaf67c9d6e29d"><code>3522341</code></a> <code>Make dependencies a const and remove extraneous resolve</code></li>
<li><a href="https://urls.greenkeeper.io/steelbrain/package-deps/commit/cf84ece1bd1caf1e77d9e77d00cd6c72bd626df0"><code>cf84ece</code></a> <code>Refactor notification</code></li>
</ul>
<p>There are 19 commits in total. See the <a href="https://urls.greenkeeper.io/steelbrain/package-deps/compare/9925769d7c45b7e74900f0eab4eff72e21ff152e...85b3cdb90d8a30ce9538dfc828120510a750a653">full diff</a>.</p>
</details>

<details>
<summary>Not sure how things should work exactly?</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html) and of course you may always [ask my humans](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by andystanton**
https://greenkeeper.io/

Fixes #56.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Cancelled the build of 58cb16f since it is superseded by 7cc6bac.

**Comment by Arcanemagus** [comment]
What do you think about just cutting macOS testing? It's _extremely_ rare that anything comes up, and Travis-CI has gotten unbearably slow with their macOS builds lately.

**Comment by Arcanemagus** [comment]
@andystanton Any objection to just cutting out the OSX builds entirely?

**Comment by andystanton** [comment]
@Arcanemagus that sounds like a good idea. Travis build problems aside, one of the problems with the build script goes away when scala 2.12.2 is available through homebrew.

**Pull request merged**
